In [102]:
import numpy as np
import pandas as pd
from scipy.optimize import fmin

In [103]:
%run optimizer.py

# Import dat

In [104]:
df = pd.read_csv('data/heart.csv',delimiter=';')
df['oldpeak'] = df['oldpeak'].str.replace(',','.')
df['bias'] = 1

In [105]:
df.head()

age  trestbps  chol  thalach oldpeak  target,  bias
0   63       145   233      150     2.1        1     1
1   37       130   250      187     3.5        1     1
2   41       130   204      172     1.4        1     1
3   56       120   236      178     0.8        1     1
4   57       120   354      163     0.6        1     1

In [106]:
v = df['target,'].values.astype('float')
df.drop(['target,'],axis=1,inplace=True)
u = df.values.astype('float')

# Generating J(x)

In [107]:
def J(x):
    return np.sum([ (1-v[i])*x@u[i,:] + np.log(1+np.exp(- x@u[i,:])) for i in range(v.shape[0]) ])

def dJ(x):
    return np.sum(np.array([ (1-v[i])*u[i,:] -(u[i,:]/(np.exp(x@u[i,:])+1)) for i in range(v.shape[0]) ]),axis=0)

In [108]:
x0 = np.zeros(6)
x0[0] = -2.28

In [109]:
optimize(x0=x0, f=J, df=dJ, method='BFGS', optimal_step=False)

<ipython-input-107-97fc82834ffa>:2: RuntimeWarning: overflow encountered in exp
  return np.sum([ (1-v[i])*x@u[i,:] + np.log(1+np.exp(- x@u[i,:])) for i in range(v.shape[0]) ])


array([-8.27932779e-03, -1.59163073e-02, -3.92257647e-04,  3.82257616e-02,
       -5.91209418e-01, -2.28912802e+00])

In [111]:
optimize(x0=x0, f=J, df=dJ, method='DFP', optimal_step=False)

<ipython-input-107-97fc82834ffa>:2: RuntimeWarning: overflow encountered in exp
  return np.sum([ (1-v[i])*x@u[i,:] + np.log(1+np.exp(- x@u[i,:])) for i in range(v.shape[0]) ])


array([-8.27935300e-03, -1.59163190e-02, -3.92260304e-04,  3.82257475e-02,
       -5.91209323e-01, -2.28912240e+00])

In [112]:
optimize(x0=x0, f=J, df=dJ, method='BFGS', optimal_step=True)

<ipython-input-107-97fc82834ffa>:5: RuntimeWarning: overflow encountered in exp
  return np.sum(np.array([ (1-v[i])*u[i,:] -(u[i,:]/(np.exp(x@u[i,:])+1)) for i in range(v.shape[0]) ]),axis=0)


array([-8.27936384e-03, -1.59163024e-02, -3.92260278e-04,  3.82257501e-02,
       -5.91209196e-01, -2.28912450e+00])

In [113]:
optimize(x0=x0, f=J, df=dJ, method='DFP', optimal_step=True)

<ipython-input-107-97fc82834ffa>:5: RuntimeWarning: overflow encountered in exp
  return np.sum(np.array([ (1-v[i])*u[i,:] -(u[i,:]/(np.exp(x@u[i,:])+1)) for i in range(v.shape[0]) ]),axis=0)


array([-8.27935464e-03, -1.59163174e-02, -3.92259871e-04,  3.82257468e-02,
       -5.91209353e-01, -2.28912248e+00])

In [114]:
fmin(J,x0)

Optimization terminated successfully.
         Current function value: 153.453454
         Iterations: 218
         Function evaluations: 372


array([-0.07254204,  0.00668163,  0.00020864,  0.0220571 , -0.02318095,
       -0.02239947])

In [116]:
J(np.array([-0.07254204,  0.00668163,  0.00020864,  0.0220571 , -0.02318095,
       -0.02239947]))

153.45345070550587

In [117]:
J(np.array([-8.27935464e-03, -1.59163174e-02, -3.92259871e-04,  3.82257468e-02,
       -5.91209353e-01, -2.28912248e+00]))

133.96188501425559