In [95]:
import numpy as np
from scipy.optimize import fmin

In [96]:
%run optimizer.py

In [97]:
def f(x, a=10):
    A = np.diag((1, a))
    h = np.array((-a, -a**2))
    return 0.5 * x@A@x + h@x

def df(x, a=10):
    A = np.diag((1, a))
    h = np.array((-a, -a**2))
    return A@x + h

In [98]:
optimize(x0=np.array([0,0]), f=f, df=df, method='BFGS', optimal_step=False)

array([9.99995048, 9.99997503])

In [99]:
optimize(x0=np.array([0,0]), f=f, df=df, method='DFP', optimal_step=False)

array([9.99999949, 9.99999975])

In [100]:
optimize(x0=np.array([0,0]), f=f, df=df, method='BFGS', optimal_step=True)

array([10.00000105,  9.99999972])

In [101]:
optimize(x0=np.array([0,0]), f=f, df=df, method='DFP', optimal_step=True)

array([9.99929986, 9.99997639])

In [102]:
fmin(f,np.array([0,0]))

Optimization terminated successfully.
         Current function value: -550.000000
         Iterations: 86
         Function evaluations: 162


array([10.00002817,  9.99998074])